export const bookmarkEmpty = <i className="fa-regular fa-bookmark" />;
export const bookmarkFilled = <i className="fa-solid fa-bookmark" />;
export const copy = <i className="fa-regular fa-copy" />;
export const heart = <i className="fa-solid fa-heart" />;
export const heartOutline = <i className="fa-regular fa-heart" />;
export const home = <i className="fa-solid fa-house" />;
export const bookmarkIcon = <i className="fa-solid fa-bookmark" />;
export const box = <i className="fa-solid fa-box" />;
export const help = <i className="fa-solid fa-circle-info" />;
export const gear = <i className="fa-solid fa-gear" />;
export const users = <i className="fa-solid fa-user-group" />;
export const fire = <i className="fa-solid fa-fire-flame-curved" />;
export const signout = <i className="fa-solid fa-right-from-bracket" />;
export const github = <i className="fa-brands fa-github" />;
export const linkedin = <i className="fa-brands fa-linkedin" />;
export const envelope = <i className="fa-solid fa-envelope" />;
export const arrowLeft = <i className="fa-solid fa-arrow-left fa-beat-fade" />;
export const bars = <i className="fa-solid fa-bars fa-beat" />;
export const trash = <i className="fa-solid fa-trash" />;
export const edit = <i className="fa-solid fa-pen-to-square" />;
export const login = <i className="fa-solid fa-right-to-bracket" />;
export const register = <i className="fa-solid fa-user-plus" />;
export const down = <i className="fa-solid fa-chevron-down" />;
export const up = <i className="fa-solid fa-chevron-up" />;
export const prev = <i className="fa-solid fa-backward" />;
export const next = <i className="fa-solid fa-forward" />;
export const plus = <i className="fa-solid fa-plus" />;
export const cross = <i className="fa-solid fa-x" />;
